SELECT L.CHAVELCTOCTB, L.DATALCTOCTB, L.VALORLCTOCTB, L.CONTACTBDEB, L.CONTACTBCRED, L.COMPLHIST
FROM LCTOCTB L
WHERE L.DATALCTOCTB >= ':firstYear-01-01' 
AND L.DATALCTOCTB <= ':lastYear-12-31' 
AND L.CODIGOEMPRESA = :enterpriseCode
AND L.CODIGOORIGLCTOCTB <> 'FP'